### ISSUE TITLE
[Logcat]: SamSprung #3f026ce

### ISSUE THREAD

**Issue by LogcatGitHub** [SamSprung/SamSprung-TooUI#212] opened 2022-10-29 16:49 UTC
*Submitted by seunogat@*****.com*

Description:
---

Please how do I hide unwanted apps on the cover screen ? There is no application drawer. All my apps are displayed on the cover screen 

Device info:
---
<table>
<tr><td>App version</td><td>2.1.4</td></tr>
<tr><td>App version code</td><td>214</td></tr>
<tr><td>Android build version</td><td>F711BXXS3CVIG</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>32</td></tr>
<tr><td>Android build ID</td><td>SP2A.220305.013.F711BXXS3CVIG</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>b2q</td></tr>
<tr><td>Device model</td><td>SM-F711B</td></tr>
<tr><td>Device product name</td><td>b2qxeea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Logcat:
---
```
SamSprung (google) #3f026ce
Android S_V2 (12)
Secure Lock Screen

--------- beginning of main
10-29 17:45:05.220  2999  2999 W PropertyValuesHolder: Method set() with type float not found on target class class me.zhanghai.android.materialprogressbar.IndeterminateHorizontalProgressDrawable$RectTransformX
10-29 17:45:05.277  2999  2999 W IInputConnectionWrapper: requestCursorAnchorInfo on inactive InputConnection
10-29 17:45:06.342  2999  2999 D AndroidRuntime: Shutting down VM
--------- beginning of crash
10-29 17:45:06.344  2999  2999 E AndroidRuntime: FATAL EXCEPTION: main
10-29 17:45:06.344  2999  2999 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 2999
10-29 17:45:06.344  2999  2999 E AndroidRuntime: java.lang.NullPointerException: uriString
10-29 17:45:06.344  2999  2999 E AndroidRuntime: 	at android.net.Uri$StringUri.<init>(Uri.java:507)
10-29 17:45:06.344  2999  2999 E AndroidRuntime: 	at android.net.Uri$StringUri.<init>(Uri.java:497)
10-29 17:45:06.344  2999  2999 E AndroidRuntime: 	at android.net.Uri.parse(Uri.java:469)
10-29 17:45:06.344  2999  2999 E AndroidRuntime: 	at com.heinrichreimersoftware.androidissuereporter.IssueReporterActivity$ReportIssueTask.onPostExecute(IssueReporterActivity.java:170)
10-29 17:45:06.344  2999  2999 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:771)
10-29 17:45:06.344  2999  2999 E AndroidRuntime: 	at android.os.AsyncTask.access$900(AsyncTask.java:199)
10-29 17:45:06.344  2999  2999 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
10-29 17:45:06.344  2999  2999 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-29 17:45:06.344  2999  2999 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
10-29 17:45:06.344  2999  2999 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
10-29 17:45:06.344  2999  2999 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8855)
10-29 17:45:06.344  2999  2999 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-29 17:45:06.344  2999  2999 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
10-29 17:45:06.344  2999  2999 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
10-29 17:46:27.074 21214 21214 E prung:SamSprun: Not starting debugger since process cannot load the jdwp agent.
10-29 17:46:27.077 21214 21214 E USNET   : USNET: appName: com.eightbit.samsprung:SamSprung
10-29 17:46:27.142 21214 21214 W ziparchive: Unable to open '/data/app/~~Fxr9h9sP84O17Js8xxax7A==/com.eightbit.samsprung-MIG3Xitd97wd7Ax02ihdbw==/split_config.arm64_v8a.dm': No such file or directory
10-29 17:46:27.142 21214 21214 W ziparchive: Unable to open '/data/app/~~Fxr9h9sP84O17Js8xxax7A==/com.eightbit.samsprung-MIG3Xitd97wd7Ax02ihdbw==/split_config.arm64_v8a.dm': No such file or directory
10-29 17:46:27.142 21214 21214 W prung:SamSprun: Entry not found
10-29 17:46:27.147 21214 21214 W ziparchive: Unable to open '/data/app/~~Fxr9h9sP84O17Js8xxax7A==/com.eightbit.samsprung-MIG3Xitd97wd7Ax02ihdbw==/split_config.en.dm': No such file or directory
10-29 17:46:27.147 21214 21214 W ziparchive: Unable to open '/data/app/~~Fxr9h9sP84O17Js8xxax7A==/com.eightbit.samsprung-MIG3Xitd97wd7Ax02ihdbw==/split_config.en.dm': No such file or directory
10-29 17:46:27.147 21214 21214 W prung:SamSprun: Entry not found
10-29 17:46:27.148 21214 21214 W ziparchive: Unable to open '/data/app/~~Fxr9h9sP84O17Js8xxax7A==/com.eightbit.samsprung-MIG3Xitd97wd7Ax02ihdbw==/split_config.xxhdpi.dm': No such file or directory
10-29 17:46:27.148 21214 21214 W ziparchive: Unable to open '/data/app/~~Fxr9h9sP84O17Js8xxax7A==/com.eightbit.samsprung-MIG3Xitd97wd7Ax02ihdbw==/split_config.xxhdpi.dm': No such file or directory
10-29 17:46:27.148 21214 21214 W prung:SamSprun: Entry not found
10-29 17:46:27.155 21214 21214 W prung:SamSprun: JIT profile information will not be recorded: profile file does not exist.
10-29 17:46:27.155 21214 21214 W prung:SamSprun: JIT profile information will not be recorded: profile file does not exist.
10-29 17:46:27.156 21214 21214 W prung:SamSprun: JIT profile information will not be recorded: profile file does not exist.
10-29 17:46:27.159 21214 21214 E prung:SamSprun: Failed to open file '/data/resource-cache/data@resource-cache@android-SemWT_G_MonetPalette-GX6Y.frro@idmap': No such file or directory
10-29 17:46:27.159 21214 21214 E prung:SamSprun: failed to read IDMAP /data/resource-cache/data@resource-cache@android-SemWT_G_MonetPalette-GX6Y.frro@idmap
10-29 17:46:27.160 21214 21214 W ResourcesManager: failed to preload asset path '/data/resource-cache/android-SemWT_G_MonetPalette-GX6Y.frro'
10-29 17:46:27.160 21214 21214 W ResourcesManager: java.io.IOException: Failed to load asset path /data/resource-cache/data@resource-cache@android-SemWT_G_MonetPalette-GX6Y.frro@idmap
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.content.res.ApkAssets.nativeLoad(Native Method)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.content.res.ApkAssets.<init>(ApkAssets.java:295)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.content.res.ApkAssets.loadOverlayFromPath(ApkAssets.java:215)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:528)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:499)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.access$000(ResourcesManager.java:99)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:206)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.createApkAssetsSupplierNotLocked(ResourcesManager.java:1368)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.getResources(ResourcesManager.java:1567)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.getResources(ResourcesManager.java:1500)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.LoadedApk.getResources(LoadedApk.java:1395)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3191)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3183)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7581)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ActivityThread.access$1700(ActivityThread.java:324)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.os.Looper.loopOnce(Looper.java:226)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.os.Looper.loop(Looper.java:313)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ActivityThread.main(ActivityThread.java:8855)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at java.lang.reflect.Method.invoke(Native Method)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
10-29 17:46:27.160 21214 21214 E prung:SamSprun: Failed to open file '/data/resource-cache/data@resource-cache@android-SemWT_G_MonetPalette-GX6Y.frro@idmap': No such file or directory
10-29 17:46:27.160 21214 21214 E prung:SamSprun: failed to read IDMAP /data/resource-cache/data@resource-cache@android-SemWT_G_MonetPalette-GX6Y.frro@idmap
10-29 17:46:27.160 21214 21214 W ResourcesManager: failed to add overlay path '/data/resource-cache/android-SemWT_G_MonetPalette-GX6Y.frro'
10-29 17:46:27.160 21214 21214 W ResourcesManager: java.io.IOException: Failed to load asset path /data/resource-cache/data@resource-cache@android-SemWT_G_MonetPalette-GX6Y.frro@idmap
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.content.res.ApkAssets.nativeLoad(Native Method)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.content.res.ApkAssets.<init>(ApkAssets.java:295)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.content.res.ApkAssets.loadOverlayFromPath(ApkAssets.java:215)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:528)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:499)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.access$000(ResourcesManager.java:99)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:206)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:606)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:859)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.findOrCreateResourcesImplForKeyLocked(ResourcesManager.java:929)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.createResources(ResourcesManager.java:1404)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.getResources(ResourcesManager.java:1596)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.getResources(ResourcesManager.java:1500)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.LoadedApk.getResources(LoadedApk.java:1395)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3191)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3183)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7581)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ActivityThread.access$1700(ActivityThread.java:324)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.os.Looper.loopOnce(Looper.java:226)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.os.Looper.loop(Looper.java:313)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at android.app.ActivityThread.main(ActivityThread.java:8855)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at java.lang.reflect.Method.invoke(Native Method)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
10-29 17:46:27.160 21214 21214 W ResourcesManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
10-29 17:46:27.416 21214 21214 W ziparchive: Unable to open '/data/app/~~73N_3cz7-1ewjbT49A3Y2Q==/com.google.android.trichromelibrary_524912634-TuXch_Vt-h8R8AKfdxPvYA==/base.dm': No such file or directory
10-29 17:46:27.416 21214 21214 W ziparchive: Unable to open '/data/app/~~73N_3cz7-1ewjbT49A3Y2Q==/com.google.android.trichromelibrary_524912634-TuXch_Vt-h8R8AKfdxPvYA==/base.dm': No such file or directory
10-29 17:46:27.416 21214 21214 W prung:SamSprun: Entry not found
10-29 17:46:27.428 21214 21214 E prung:SamSprun: Failed to open APK '/data/resource-cache/android-SemWT_G_MonetPalette-iMbO.frro': Invalid file
10-29 17:46:27.462 21214 21214 E prung:SamSprun: Failed to open file '/data/resource-cache/data@resource-cache@android-SemWT_G_MonetPalette-GX6Y.frro@idmap': No such file or directory
10-29 17:46:27.462 21214 21214 E prung:SamSprun: failed to read IDMAP /data/resource-cache/data@resource-cache@android-SemWT_G_MonetPalette-GX6Y.frro@idmap
10-29 17:46:27.462 21214 21214 W ResourcesManager: failed to add overlay path '/data/resource-cache/android-SemWT_G_MonetPalette-GX6Y.frro'
10-29 17:46:27.462 21214 21214 W ResourcesManager: java.io.IOException: Failed to load asset path /data/resource-cache/data@resource-cache@android-SemWT_G_MonetPalette-GX6Y.frro@idmap
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.content.res.ApkAssets.nativeLoad(Native Method)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.content.res.ApkAssets.<init>(ApkAssets.java:295)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.content.res.ApkAssets.loadOverlayFromPath(ApkAssets.java:215)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:528)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:499)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:606)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:859)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.findOrCreateResourcesImplForKeyLocked(ResourcesManager.java:929)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.findOrCreateResourcesImplForKeyLocked(ResourcesManager.java:918)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.redirectResourcesToNewImplLocked(ResourcesManager.java:2122)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.ResourcesManager.appendLibAssetsForMainAssetPath(ResourcesManager.java:2000)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.webkit.WebViewDelegate.addWebViewAssetPath(WebViewDelegate.java:199)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at com.android.webview.chromium.WebViewChromiumFactoryProvider.addWebViewAssetPath(chromium-TrichromeWebViewGoogle6432.aab-stable-524912634:271)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at com.android.webview.chromium.WebViewChromium.<init>(chromium-TrichromeWebViewGoogle6432.aab-stable-524912634:259)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at com.android.webview.chromium.WebViewChromiumFactoryProvider.createWebView(chromium-TrichromeWebViewGoogle6432.aab-stable-524912634:673)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.webkit.WebView.ensureProviderCreated(WebView.java:2590)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.webkit.WebView.setOverScrollMode(WebView.java:2677)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.view.View.<init>(View.java:5589)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.view.View.<init>(View.java:5764)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.view.ViewGroup.<init>(ViewGroup.java:720)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:58)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.webkit.WebView.<init>(WebView.java:423)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.webkit.WebView.<init>(WebView.java:365)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.webkit.WebView.<init>(WebView.java:347)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.webkit.WebView.<init>(WebView.java:334)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.view.LayoutInflater.createView(LayoutInflater.java:780)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:934)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:954)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:9)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:2)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at com.eightbit.samsprung.settings.CoverPreferences.onCreate(CoverPreferences.kt:29)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.Activity.performCreate(Activity.java:8326)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.Activity.performCreate(Activity.java:8306)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1347)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4212)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4403)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:104)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2498)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.os.Looper.loopOnce(Looper.java:226)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.os.Looper.loop(Looper.java:313)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at android.app.ActivityThread.main(ActivityThread.java:8855)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at java.lang.reflect.Method.invoke(Native Method)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
10-29 17:46:27.462 21214 21214 W ResourcesManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
10-29 17:46:27.497 21214 21257 W chromium: [WARNING:dns_config_service_android.cc(115)] Failed to read DnsConfig.
10-29 17:46:27.928 21214 21283 W cr_media: BLUETOOTH_CONNECT permission is missing.
10-29 17:46:27.928 21214 21283 W cr_media: registerBluetoothIntentsIfNeeded: Requires BLUETOOTH permission
10-29 17:46:37.233 21214 21224 W JavaBinder: BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.google.android.play.core.internal.zzai
```

**Comment by AbandonedCart** [comment] 2022-10-29 17:03
```
10-27 23:22:59.762  2999  3827 E AndroidRuntime: FATAL EXCEPTION: pool-1417-thread-1
10-27 23:22:59.762  2999  3827 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 2999
10-27 23:22:59.762  2999  3827 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{af9e7c2} (736c07f0-b950-49e5-bf5d-64de29c5949c) not attached to an activity.
10-27 23:22:59.762  2999  3827 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
10-27 23:22:59.762  2999  3827 E AndroidRuntime: 	at com.eightbit.samsprung.launcher.AppDrawerFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:31)
10-27 23:22:59.762  2999  3827 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-27 23:22:59.762  2999  3827 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-27 23:22:59.762  2999  3827 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-27 23:28:12.097  2999  8111 E AndroidRuntime: FATAL EXCEPTION: pool-1666-thread-1
10-27 23:28:12.097  2999  8111 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 2999
10-27 23:28:12.097  2999  8111 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{c99cabf} (984bca0d-6840-444e-8b16-1b435153eccc) not attached to an activity.
10-27 23:28:12.097  2999  8111 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
10-27 23:28:12.097  2999  8111 E AndroidRuntime: 	at com.eightbit.samsprung.launcher.AppDrawerFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:31)
10-27 23:28:12.097  2999  8111 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-27 23:28:12.097  2999  8111 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-27 23:28:12.097  2999  8111 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by AbandonedCart** [comment] 2022-10-29 17:36
Pushed the current code to Google Play. It may not fix the issue, but will get everything lined up.

**Comment by AbandonedCart** [comment] 2022-10-29 18:24
> Please how do I hide unwanted apps on the cover screen ? There is no application drawer. All my apps are displayed on the cover screen

Apps are hidden by running the app from the main screen. At the bottom of the settings page is a pull up drawer with all the apps listed. Click the toggle next to any you want to hide. This is explained at  https://samsprung.github.io/launcher/index.html?s=Launcher%20App&d=App%20Display

**Comment by AbandonedCart** [comment] 2022-10-30 01:16
To break it down, the apps are launching a splash screen activity and then transitioning to something else. That transition is what is breaking the launcher's ability to kill the app, which is locking the phone in portrait. Killing the app from the background will restore the launcher, but also requires opening the screen. The current workaround isn't "effective" enough and there may not be access to anything better without accessibility and / or "dangerous" permissions.

The problem is that, fundamentally, this is a launcher. It isn't actually a launcher, though. It's nothing more than an app in the eyes of the phone. Marking it as a launcher means the cover screen blocks it. Not marking it as a launcher means it can't access the launcher functionality. It's more or less putting a launcher on a microwave. It's not meant to be there.

This may end up being something that can only be supported on GitHub releases because part of Google Play is the absurd number of restrictions on what you can and can't do based on nothing more than their opinion of necessity. Obviously, they aren't going to think an app doing stuff to act like a launcher and not labeled a launcher is unnecessary.

**Closed as completed** 2023-05-02 22:06 UTC
