### ISSUE TITLE
Logcat - SamSprung #130654c

### ISSUE THREAD

**Issue by LogcatGitHub** [SamSprung/SamSprung-TooUI#163] opened 2022-05-10 12:46 UTC
*Submitted by lilacrose@*******.com*

Description:
---

The app doesn't show if I search the app from search bar.

Device info:
---
<table>
<tr><td>App version</td><td>1.7.4</td></tr>
<tr><td>App version code</td><td>174</td></tr>
<tr><td>Android build version</td><td>F711BXXS2CVC9</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SP1A.210812.016.F711BXXS2CVC9</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>b2q</td></tr>
<tr><td>Device model</td><td>SM-F711B</td></tr>
<tr><td>Device product name</td><td>b2qxxx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Logcat:
---
```SamSprung - #130654c
Android S (12)
Secure Lock Screen

--------- beginning of crash
05-10 13:39:57.201 27626 27626 E AndroidRuntime: FATAL EXCEPTION: main
05-10 13:39:57.201 27626 27626 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 27626
05-10 13:39:57.201 27626 27626 E AndroidRuntime: java.lang.NullPointerException: uriString
05-10 13:39:57.201 27626 27626 E AndroidRuntime: 	at android.net.Uri$StringUri.<init>(Uri.java:507)
05-10 13:39:57.201 27626 27626 E AndroidRuntime: 	at android.net.Uri$StringUri.<init>(Uri.java:497)
05-10 13:39:57.201 27626 27626 E AndroidRuntime: 	at android.net.Uri.parse(Uri.java:469)
05-10 13:39:57.201 27626 27626 E AndroidRuntime: 	at com.heinrichreimersoftware.androidissuereporter.IssueReporterActivity$ReportIssueTask.onPostExecute(IssueReporterActivity.java:14)
05-10 13:39:57.201 27626 27626 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:771)
05-10 13:39:57.201 27626 27626 E AndroidRuntime: 	at android.os.AsyncTask.access$900(AsyncTask.java:199)
05-10 13:39:57.201 27626 27626 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
05-10 13:39:57.201 27626 27626 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-10 13:39:57.201 27626 27626 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
05-10 13:39:57.201 27626 27626 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
05-10 13:39:57.201 27626 27626 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
05-10 13:39:57.201 27626 27626 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-10 13:39:57.201 27626 27626 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
05-10 13:39:57.201 27626 27626 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
--------- beginning of main
05-10 17:54:46.500 31613 32306 I CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client com.twitter.android API Level 1
05-10 17:54:47.176 31613 32306 I CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.twitter.android API Level 1
05-10 17:54:48.306 31613 12595 I CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.twitter.android API Level 1
05-10 17:54:48.515 31613 12595 I CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client com.twitter.android API Level 1
05-10 17:55:18.195 31613 12595 I CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client com.whatsapp API Level 2
05-10 17:55:18.555 31613 12595 I CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.whatsapp API Level 2
05-10 17:55:19.885 31613 12595 I CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.whatsapp API Level 2
05-10 17:55:20.096 31613 12595 I CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client com.whatsapp API Level 2
05-10 17:56:05.626 31613 32199 I CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client com.whatsapp API Level 2
05-10 17:56:05.945 31613 32199 I CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.whatsapp API Level 2
05-10 17:56:06.801 31613 12595 I CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.whatsapp API Level 2
05-10 17:56:06.981 31613 12595 I CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client com.whatsapp API Level 2
05-10 17:56:12.566 31613 32306 I CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client com.whatsapp API Level 2
05-10 17:56:12.821 31613 32306 I CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.whatsapp API Level 2
05-10 17:56:13.238 31613 32306 I CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.whatsapp API Level 2
05-10 17:56:13.418 31613 32306 I CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client com.whatsapp API Level 2
05-10 18:07:09.039 31613 32306 I CameraManagerGlobal: Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_OPEN for client com.samsung.android.smartface API Level 2
05-10 18:07:09.299 31613 32306 I CameraManagerGlobal: Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_ACTIVE for client com.samsung.android.smartface API Level 2
05-10 18:07:09.629 31613 32306 I CameraManagerGlobal: Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_IDLE for client com.samsung.android.smartface API Level 2
05-10 18:07:09.763 31613 32306 I CameraManagerGlobal: Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.samsung.android.smartface API Level 2
05-10 18:14:23.461 31613 31613 I DecorView: [INFO] isPopOver=false, config=true
05-10 18:14:23.461 31613 31613 I DecorView: updateCaptionType >> DecorView@5652665[], isFloating=false, isApplication=true, hasWindowControllerCallback=true, hasWindowDecorCaption=false
05-10 18:14:23.461 31613 31613 D DecorView: setCaptionType = 0, this = DecorView@5652665[]
05-10 18:14:23.465 31613 31613 I DecorView: getCurrentDensityDpi: from real metrics. densityDpi=480 msg=resources_loaded
05-10 18:14:25.168 31613 31638 D NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
05-10 18:14:25.169 31613 31613 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
05-10 18:14:25.173 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: setView = com.android.internal.policy.DecorView@5652665 TM=true
05-10 18:14:25.186 31613 31613 D skia    : --- Failed to create image decoder with message 'unimplemented'
05-10 18:14:25.192 31613 31613 D WallpaperManager: peekWallpaperBitmap: which =1, useCache = true
05-10 18:14:25.192 31613 31613 D WallpaperManager: peekWallpaperBitmap() cached image height=2560 width=2560
05-10 18:14:25.259 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=30 res=0x7 s={true 540420947424} ch=true fn=-1
05-10 18:14:25.263 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11374 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:2893 
05-10 18:14:25.265 31613 31638 D OpenGLRenderer: eglCreateWindowSurface
05-10 18:14:25.352 31613 31621 W prung:SamSprun: Reducing the number of considered missed Gc histogram windows from 182 to 100
05-10 18:14:25.354 31613 31638 I BufferQueueProducer: [ViewRootImpl@df1917c[CoverPreferences]#2(BLAST Consumer)2](id:7b7d00000002,api:1,p:31613,c:31613) queueBuffer: queued for the first time.
05-10 18:14:25.356 31613 31638 D OpenGLRenderer: GPIS:: SetUp Pid : 31613    Tid : 31638
05-10 18:14:25.359 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
05-10 18:14:25.359 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: [DP] rdf()
05-10 18:14:25.359 31613 31613 D ViewRootImpl@df1917c[CoverPreferences]: reportDrawFinished (fn: -1) 
05-10 18:14:25.396 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
05-10 18:14:25.404 31613 31613 D InputMethodManager: startInputInner - Id : 0
05-10 18:14:25.404 31613 31613 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
05-10 18:14:25.424 31613 31613 D InputMethodManager: startInputInner - Id : 0
05-10 18:14:26.913 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: ViewPostIme pointer 0
05-10 18:14:27.076 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: ViewPostIme pointer 1
05-10 18:14:29.006 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: ViewPostIme pointer 0
05-10 18:14:29.185 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: ViewPostIme pointer 1
05-10 18:14:29.230 31613 31613 D InputMethodManager: startInputInner - Id : 0
05-10 18:14:29.230 31613 31613 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
05-10 18:14:29.232 31613 31613 I IMM_LC  : hsifw() - flags=0, caller=android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow:1846 org.chromium.content.browser.input.ImeAdapterImpl.i:174 org.chromium.content.browser.input.ImeAdapterImpl.updateState:525 android.os.MessageQueue.nativePollOnce:-2 android.os.MessageQueue.next:335 
05-10 18:14:29.232 31613 31613 I IMM_LC  : hideSoftInputFromWindow - mService.hideSoftInput
05-10 18:14:29.345 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 0 1
05-10 18:14:29.665 31613 31613 D InputTransport: Input channel destroyed: 'ClientS', fd=147
05-10 18:14:30.044 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: handleAppVisibility mAppVisible=true visible=false
05-10 18:14:30.060 31613 31638 D OpenGLRenderer: setSurface called with nullptr
05-10 18:14:30.060 31613 31638 D OpenGLRenderer: setSurface() destroyed EGLSurface
05-10 18:14:30.060 31613 31638 D OpenGLRenderer: destroyEglSurface
05-10 18:14:30.065 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=4 res=0x5 s={false 0} ch=true fn=35
05-10 18:14:30.070 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: stopped(true) old=false
05-10 18:14:30.079 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=6 res=0x5 s={false 0} ch=false fn=-1
05-10 18:15:20.375 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: handleAppVisibility mAppVisible=false visible=true
05-10 18:15:20.386 31613 31638 D OpenGLRenderer: setSurface called with nullptr
05-10 18:15:20.422 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)4 dur=33 res=0x1 s={false 0} ch=false fn=-1
05-10 18:15:20.443 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: stopped(false) old=true
05-10 18:15:20.448 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: stopped(false) old=false
05-10 18:15:20.448 31613 31613 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
05-10 18:15:20.453 31613 31638 D OpenGLRenderer: setSurface called with nullptr
05-10 18:15:20.460 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=7 res=0x7 s={true 540420947424} ch=true fn=-1
05-10 18:15:20.461 31613 31638 D OpenGLRenderer: eglCreateWindowSurface
05-10 18:15:20.461 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11374 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:2893 
05-10 18:15:20.507 31613 31638 I BufferQueueProducer: [ViewRootImpl@df1917c[CoverPreferences]#3(BLAST Consumer)3](id:7b7d00000003,api:1,p:31613,c:31613) queueBuffer: queued for the first time.
05-10 18:15:20.509 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
05-10 18:15:20.509 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: [DP] rdf()
05-10 18:15:20.509 31613 31613 D ViewRootImpl@df1917c[CoverPreferences]: reportDrawFinished (fn: -1) 
05-10 18:15:20.510 31613 31613 D skia    : --- Failed to create image decoder with message 'unimplemented'
05-10 18:15:20.513 31613 31613 D WallpaperManager: peekWallpaperBitmap: which =1, useCache = true
05-10 18:15:20.513 31613 31613 D WallpaperManager: peekWallpaperBitmap() cached image height=2560 width=2560
05-10 18:15:20.526 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
05-10 18:15:20.527 31613 31613 D InputMethodManager: startInputInner - Id : 0
05-10 18:15:20.527 31613 31613 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
05-10 18:15:21.170 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: ViewPostIme pointer 0
05-10 18:15:21.290 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: ViewPostIme pointer 1
05-10 18:15:23.484 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: ViewPostIme pointer 0
05-10 18:15:23.559 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: ViewPostIme pointer 1
05-10 18:15:24.702 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: ViewPostIme pointer 0
05-10 18:15:24.799 31613 31613 I ViewRootImpl@df1917c[CoverPreferences]: ViewPostIme pointer 1
```

**Comment by AbandonedCart** [comment] 2022-05-10 12:59
Duplicate of https://github.com/SamSprung/SamSprung-TooUI/issues/162

**Closed by AbandonedCart** 2022-05-10 12:59 UTC
