### ISSUE TITLE
Logcat - SamSprung #6e4e048

### ISSUE THREAD

**Issue by LogcatGitHub** [SamSprung/SamSprung-TooUI#140] opened 2022-04-22 23:50 UTC
*Submitted by Kanokrada.tungkamanee@*****.com*

Description:
---

Kanokrada.tungkamanee@gmail.com 

Device info:
---
<table>
<tr><td>App version</td><td>1.6.3</td></tr>
<tr><td>App version code</td><td>163</td></tr>
<tr><td>Android build version</td><td>F711BXXS2CVC9</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SP1A.210812.016.F711BXXS2CVC9</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>b2q</td></tr>
<tr><td>Device model</td><td>SM-F711B</td></tr>
<tr><td>Device product name</td><td>b2qxxx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Logcat:
---
```SamSprung - #6e4e048
Android S (12)
Secure Lock Screen

--------- beginning of main
04-23 06:45:15.419 31920 31945 D OpenGLRenderer: setSurface called with nullptr
04-23 06:45:15.419 31920 31945 D OpenGLRenderer: setSurface() destroyed EGLSurface
04-23 06:45:15.419 31920 31945 D OpenGLRenderer: destroyEglSurface
04-23 06:45:15.422 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=1 res=0x5 s={false 0} ch=true fn=1430
04-23 06:45:15.428 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: stopped(true) old=false
04-23 06:45:15.436 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=2 res=0x5 s={false 0} ch=false fn=-1
04-23 06:45:17.742 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: handleAppVisibility mAppVisible=false visible=true
04-23 06:45:17.750 31920 31945 D OpenGLRenderer: setSurface called with nullptr
04-23 06:45:17.754 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)4 dur=4 res=0x1 s={false 0} ch=false fn=-1
04-23 06:45:17.759 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: stopped(false) old=true
04-23 06:45:17.760 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: stopped(false) old=false
04-23 06:45:17.761 31920 31920 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
04-23 06:45:17.768 31920 31945 D OpenGLRenderer: setSurface called with nullptr
04-23 06:45:17.789 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=18 res=0x7 s={true 488149264448} ch=true fn=-1
04-23 06:45:17.789 31920 31945 D OpenGLRenderer: eglCreateWindowSurface
04-23 06:45:17.789 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11374 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:2893 
04-23 06:45:17.812 31920 31945 I BufferQueueProducer: [ViewRootImpl@17d3528[CoverPreferences]#40(BLAST Consumer)40](id:7cb000000028,api:1,p:31920,c:31920) queueBuffer: queued for the first time.
04-23 06:45:17.813 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
04-23 06:45:17.813 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: [DP] rdf()
04-23 06:45:17.813 31920 31920 D ViewRootImpl@17d3528[CoverPreferences]: reportDrawFinished (fn: -1) 
04-23 06:45:17.819 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
04-23 06:45:17.821 31920 31920 D InputMethodManager: startInputInner - Id : 0
04-23 06:45:17.821 31920 31920 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-23 06:45:18.914 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:19.120 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:20.456 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:20.614 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:21.991 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:22.292 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:22.755 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:22.866 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:24.280 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:25.014 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:25.426 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:26.105 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:26.434 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:26.848 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:27.503 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:28.804 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:29.349 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:29.597 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:30.965 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:31.202 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:33.762 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:34.059 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:35.477 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:35.632 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:36.493 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:36.622 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:36.927 31920 31194 D ApplicationPackageManager: we has com.samsung.android.calendar class. reuse it 
04-23 06:45:36.928 31920 31194 I LiveIconLoader: [Calendar] LiveIcon - stdIconSize : 144 , targetIconSize : 144
04-23 06:45:36.929 31920 31194 W LiveIconLoader: System font not found, reverting to Roboto.
04-23 06:45:36.931 31920 31194 I LiveIconLoader: [Calendar] getLiveIcon - Date: 23
04-23 06:45:36.940 31920 31196 D ApplicationPackageManager: we has com.sec.android.app.clockpackage class. reuse it 
04-23 06:45:36.940 31920 31196 I LiveIconUtil: getLiveIcon was called in ClockPackage
04-23 06:45:36.941 31920 31196 I LiveIconUtil: getLiveIcon res = com.sec.android.app.clockpackage
04-23 06:45:36.941 31920 31196 I LiveIconUtil: stdIconSize : 144 , targetIconSize : 144
04-23 06:45:37.184 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:37.276 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:40.975 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:41.130 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:41.827 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:41.964 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:42.413 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:42.605 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:43.731 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:43.810 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:46.210 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:45:46.303 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:45:49.796 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 0 1
04-23 06:46:04.334 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
04-23 06:46:04.335 31920 31920 D InputMethodManager: startInputInner - Id : 0
04-23 06:46:04.335 31920 31920 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-23 06:46:08.482 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:46:08.573 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:46:16.373 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:46:16.894 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:46:24.780 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:46:24.870 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:46:25.557 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:46:25.669 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:46:26.841 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:46:27.168 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:46:27.855 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:46:27.993 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:46:28.049 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 0 1
04-23 06:46:28.197 31920 31920 D InputTransport: Input channel destroyed: 'ClientS', fd=167
04-23 06:46:28.591 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: handleAppVisibility mAppVisible=true visible=false
04-23 06:46:28.602 31920 31945 D OpenGLRenderer: setSurface called with nullptr
04-23 06:46:28.602 31920 31945 D OpenGLRenderer: setSurface() destroyed EGLSurface
04-23 06:46:28.603 31920 31945 D OpenGLRenderer: destroyEglSurface
04-23 06:46:28.612 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=2 res=0x5 s={false 0} ch=true fn=926
04-23 06:46:28.617 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: stopped(true) old=false
04-23 06:46:28.624 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=2 res=0x5 s={false 0} ch=false fn=-1
04-23 06:46:34.923 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: handleAppVisibility mAppVisible=false visible=true
04-23 06:46:34.930 31920 31945 D OpenGLRenderer: setSurface called with nullptr
04-23 06:46:34.933 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)4 dur=3 res=0x1 s={false 0} ch=false fn=-1
04-23 06:46:34.940 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: stopped(false) old=true
04-23 06:46:34.943 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: stopped(false) old=false
04-23 06:46:34.947 31920 31945 D OpenGLRenderer: setSurface called with nullptr
04-23 06:46:34.959 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=9 res=0x7 s={true 488149264448} ch=true fn=-1
04-23 06:46:34.959 31920 31945 D OpenGLRenderer: eglCreateWindowSurface
04-23 06:46:34.960 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11374 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:2893 
04-23 06:46:34.983 31920 31945 I BufferQueueProducer: [ViewRootImpl@17d3528[CoverPreferences]#41(BLAST Consumer)41](id:7cb000000029,api:1,p:31920,c:31920) queueBuffer: queued for the first time.
04-23 06:46:34.984 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
04-23 06:46:34.984 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: [DP] rdf()
04-23 06:46:34.984 31920 31920 D ViewRootImpl@17d3528[CoverPreferences]: reportDrawFinished (fn: -1) 
04-23 06:46:35.019 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
04-23 06:46:35.021 31920 31920 D InputMethodManager: startInputInner - Id : 0
04-23 06:46:35.021 31920 31920 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-23 06:46:35.046 31920 31930 D InputTransport: Input channel destroyed: 'ClientS', fd=184
04-23 06:46:35.206 31920 31384 D ApplicationPackageManager: we has com.sec.android.app.clockpackage class. reuse it 
04-23 06:46:35.206 31920 31384 I LiveIconUtil: getLiveIcon was called in ClockPackage
04-23 06:46:35.208 31920 31384 I LiveIconUtil: getLiveIcon res = com.sec.android.app.clockpackage
04-23 06:46:35.208 31920 31384 I LiveIconUtil: stdIconSize : 144 , targetIconSize : 144
04-23 06:46:35.212 31920 31386 D ApplicationPackageManager: we has com.samsung.android.calendar class. reuse it 
04-23 06:46:35.213 31920 31386 I LiveIconLoader: [Calendar] LiveIcon - stdIconSize : 144 , targetIconSize : 144
04-23 06:46:35.214 31920 31386 W LiveIconLoader: System font not found, reverting to Roboto.
04-23 06:46:35.216 31920 31386 I LiveIconLoader: [Calendar] getLiveIcon - Date: 23
04-23 06:46:36.640 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:46:36.781 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:46:36.829 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 0 1
04-23 06:46:36.960 31920 31920 D InputTransport: Input channel destroyed: 'ClientS', fd=192
04-23 06:46:37.351 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: handleAppVisibility mAppVisible=true visible=false
04-23 06:46:37.361 31920 31945 D OpenGLRenderer: setSurface called with nullptr
04-23 06:46:37.362 31920 31945 D OpenGLRenderer: setSurface() destroyed EGLSurface
04-23 06:46:37.362 31920 31945 D OpenGLRenderer: destroyEglSurface
04-23 06:46:37.365 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=1 res=0x5 s={false 0} ch=true fn=73
04-23 06:46:37.370 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: stopped(true) old=false
04-23 06:46:37.381 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=2 res=0x5 s={false 0} ch=false fn=-1
04-23 06:46:38.315 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: handleAppVisibility mAppVisible=false visible=true
04-23 06:46:38.319 31920 31945 D OpenGLRenderer: setSurface called with nullptr
04-23 06:46:38.328 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)4 dur=9 res=0x1 s={false 0} ch=false fn=-1
04-23 06:46:38.331 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: stopped(false) old=true
04-23 06:46:38.332 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: stopped(false) old=false
04-23 06:46:38.340 31920 31945 D OpenGLRenderer: setSurface called with nullptr
04-23 06:46:38.349 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=9 res=0x7 s={true 488149264448} ch=true fn=-1
04-23 06:46:38.350 31920 31945 D OpenGLRenderer: eglCreateWindowSurface
04-23 06:46:38.350 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11374 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:2893 
04-23 06:46:38.377 31920 31945 I BufferQueueProducer: [ViewRootImpl@17d3528[CoverPreferences]#42(BLAST Consumer)42](id:7cb00000002a,api:1,p:31920,c:31920) queueBuffer: queued for the first time.
04-23 06:46:38.378 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
04-23 06:46:38.378 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: [DP] rdf()
04-23 06:46:38.378 31920 31920 D ViewRootImpl@17d3528[CoverPreferences]: reportDrawFinished (fn: -1) 
04-23 06:46:38.399 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
04-23 06:46:38.400 31920 31920 D InputMethodManager: startInputInner - Id : 0
04-23 06:46:38.401 31920 31920 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-23 06:46:38.537 31920 31468 D ApplicationPackageManager: we has com.samsung.android.calendar class. reuse it 
04-23 06:46:38.537 31920 31468 I LiveIconLoader: [Calendar] LiveIcon - stdIconSize : 144 , targetIconSize : 144
04-23 06:46:38.537 31920 31468 W LiveIconLoader: System font not found, reverting to Roboto.
04-23 06:46:38.538 31920 31468 I LiveIconLoader: [Calendar] getLiveIcon - Date: 23
04-23 06:46:38.539 31920 31466 D ApplicationPackageManager: we has com.sec.android.app.clockpackage class. reuse it 
04-23 06:46:38.539 31920 31466 I LiveIconUtil: getLiveIcon was called in ClockPackage
04-23 06:46:38.539 31920 31466 I LiveIconUtil: getLiveIcon res = com.sec.android.app.clockpackage
04-23 06:46:38.539 31920 31466 I LiveIconUtil: stdIconSize : 144 , targetIconSize : 144
04-23 06:46:39.149 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:46:39.246 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:46:39.303 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 0 1
04-23 06:46:39.599 31920 31920 D InputTransport: Input channel destroyed: 'ClientS', fd=189
04-23 06:46:39.978 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: handleAppVisibility mAppVisible=true visible=false
04-23 06:46:39.988 31920 31945 D OpenGLRenderer: setSurface called with nullptr
04-23 06:46:39.988 31920 31945 D OpenGLRenderer: setSurface() destroyed EGLSurface
04-23 06:46:39.988 31920 31945 D OpenGLRenderer: destroyEglSurface
04-23 06:46:40.004 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=9 res=0x5 s={false 0} ch=true fn=74
04-23 06:46:40.007 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: stopped(true) old=false
04-23 06:46:40.020 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=2 res=0x5 s={false 0} ch=false fn=-1
04-23 06:47:22.310 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: handleAppVisibility mAppVisible=false visible=true
04-23 06:47:22.313 31920 31945 D OpenGLRenderer: setSurface called with nullptr
04-23 06:47:22.320 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)4 dur=6 res=0x1 s={false 0} ch=false fn=-1
04-23 06:47:22.323 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: stopped(false) old=true
04-23 06:47:22.326 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: stopped(false) old=false
04-23 06:47:22.326 31920 31920 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
04-23 06:47:22.333 31920 31945 D OpenGLRenderer: setSurface called with nullptr
04-23 06:47:22.344 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=9 res=0x7 s={true 488149264448} ch=true fn=-1
04-23 06:47:22.344 31920 31945 D OpenGLRenderer: eglCreateWindowSurface
04-23 06:47:22.344 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11374 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:2893 
04-23 06:47:22.375 31920 31945 I BufferQueueProducer: [ViewRootImpl@17d3528[CoverPreferences]#43(BLAST Consumer)43](id:7cb00000002b,api:1,p:31920,c:31920) queueBuffer: queued for the first time.
04-23 06:47:22.377 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
04-23 06:47:22.377 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: [DP] rdf()
04-23 06:47:22.377 31920 31920 D ViewRootImpl@17d3528[CoverPreferences]: reportDrawFinished (fn: -1) 
04-23 06:47:22.406 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
04-23 06:47:22.409 31920 31920 D InputMethodManager: startInputInner - Id : 0
04-23 06:47:22.409 31920 31920 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-23 06:47:25.173 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:47:25.403 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
04-23 06:47:26.582 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 0
04-23 06:47:26.635 31920 31920 I ViewRootImpl@17d3528[CoverPreferences]: ViewPostIme pointer 1
```

**Comment by AbandonedCart** [comment] 2022-04-23 01:25
Duplicate of https://github.com/SamSprung/SamSprung-TooUI/issues/138

**Closed by AbandonedCart** 2022-04-23 01:25 UTC
