### ISSUE TITLE
Logcat - SamSprung #6e4e048

### ISSUE THREAD

**Issue by LogcatGitHub** [SamSprung/SamSprung-TooUI#141] opened 2022-04-23 00:14 UTC
*Submitted by Kanokrada.tungkamanee@*****.com*

Description:
---

Kanokrada.tungkamanee@gmail.com 

Device info:
---
<table>
<tr><td>App version</td><td>1.6.3</td></tr>
<tr><td>App version code</td><td>163</td></tr>
<tr><td>Android build version</td><td>F711BXXS2CVC9</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SP1A.210812.016.F711BXXS2CVC9</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>b2q</td></tr>
<tr><td>Device model</td><td>SM-F711B</td></tr>
<tr><td>Device product name</td><td>b2qxxx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Logcat:
---
```SamSprung - #6e4e048
Android S (12)
Secure Lock Screen

--------- beginning of main
04-23 07:10:11.029  3312  3341 D NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
04-23 07:10:11.029  3312  3312 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
04-23 07:10:11.033  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: setView = com.android.internal.policy.DecorView@897c3bd TM=true
04-23 07:10:11.034  3312  3312 D skia    : --- Failed to create image decoder with message 'unimplemented'
04-23 07:10:11.036  3312  3312 D WallpaperManager: peekWallpaperBitmap: which =1, useCache = true
04-23 07:10:11.036  3312  3312 D WallpaperManager: peekWallpaperBitmap() cached image height=2640 width=1160
04-23 07:10:11.052  3312 19776 D ApplicationPackageManager: we has com.samsung.android.calendar class. reuse it 
04-23 07:10:11.053  3312 19776 I LiveIconLoader: [Calendar] LiveIcon - stdIconSize : 144 , targetIconSize : 144
04-23 07:10:11.053  3312 19776 W LiveIconLoader: System font not found, reverting to Roboto.
04-23 07:10:11.054  3312 19776 I LiveIconLoader: [Calendar] getLiveIcon - Date: 23
04-23 07:10:11.056  3312 19774 D ApplicationPackageManager: we has com.sec.android.app.clockpackage class. reuse it 
04-23 07:10:11.056  3312 19774 I LiveIconUtil: getLiveIcon was called in ClockPackage
04-23 07:10:11.060  3312 19774 I LiveIconUtil: getLiveIcon res = com.sec.android.app.clockpackage
04-23 07:10:11.060  3312 19774 I LiveIconUtil: stdIconSize : 144 , targetIconSize : 144
04-23 07:10:11.070  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=16 res=0x7 s={true 488149212128} ch=true fn=-1
04-23 07:10:11.071  3312  3341 D OpenGLRenderer: eglCreateWindowSurface
04-23 07:10:11.072  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11374 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:2893 
04-23 07:10:11.112  3312  3341 I BufferQueueProducer: [ViewRootImpl@2c048ca[CoverPreferences]#4(BLAST Consumer)4](id:cf000000004,api:1,p:3312,c:3312) queueBuffer: queued for the first time.
04-23 07:10:11.114  3312  3341 D OpenGLRenderer: GPIS:: SetUp Pid : 3312    Tid : 3341
04-23 07:10:11.115  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
04-23 07:10:11.116  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: [DP] rdf()
04-23 07:10:11.116  3312  3312 D ViewRootImpl@2c048ca[CoverPreferences]: reportDrawFinished (fn: -1) 
04-23 07:10:11.141  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
04-23 07:10:11.142  3312  3312 D InputMethodManager: startInputInner - Id : 0
04-23 07:10:11.142  3312  3312 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-23 07:10:12.599  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:10:12.708  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:10:18.049  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:10:18.152  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:10:18.521  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 0 1
04-23 07:10:18.757  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: handleAppVisibility mAppVisible=true visible=false
04-23 07:10:18.768  3312  3341 D OpenGLRenderer: setSurface called with nullptr
04-23 07:10:18.768  3312  3341 D OpenGLRenderer: setSurface() destroyed EGLSurface
04-23 07:10:18.769  3312  3341 D OpenGLRenderer: destroyEglSurface
04-23 07:10:18.784  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=5 res=0x5 s={false 0} ch=true fn=45
04-23 07:10:18.936  3312  3312 D InputTransport: Input channel destroyed: 'ClientS', fd=376
04-23 07:10:18.962  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: stopped(true) old=false
04-23 07:10:18.976  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=11 res=0x5 s={false 0} ch=false fn=-1
04-23 07:11:07.922  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: handleAppVisibility mAppVisible=false visible=true
04-23 07:11:07.936  3312  3341 D OpenGLRenderer: setSurface called with nullptr
04-23 07:11:07.940  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)4 dur=3 res=0x1 s={false 0} ch=false fn=-1
04-23 07:11:07.964  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: stopped(false) old=true
04-23 07:11:07.966  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: stopped(false) old=false
04-23 07:11:07.973  3312  3341 D OpenGLRenderer: setSurface called with nullptr
04-23 07:11:07.998  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=23 res=0x7 s={true 488149212128} ch=true fn=-1
04-23 07:11:07.998  3312  3341 D OpenGLRenderer: eglCreateWindowSurface
04-23 07:11:07.999  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11374 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:2893 
04-23 07:11:08.033  3312  3341 I BufferQueueProducer: [ViewRootImpl@2c048ca[CoverPreferences]#5(BLAST Consumer)5](id:cf000000005,api:1,p:3312,c:3312) queueBuffer: queued for the first time.
04-23 07:11:08.034  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
04-23 07:11:08.034  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: [DP] rdf()
04-23 07:11:08.034  3312  3312 D ViewRootImpl@2c048ca[CoverPreferences]: reportDrawFinished (fn: -1) 
04-23 07:11:08.049  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
04-23 07:11:08.050  3312  3312 D InputMethodManager: startInputInner - Id : 0
04-23 07:11:08.050  3312  3312 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-23 07:11:08.288  3312  3312 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=true
04-23 07:11:08.294  3312  3312 I ViewRootImpl@247cf96[SamSprungOverlay]: Relayout returned: old=(0,0,512,260) new=(0,0,512,260) req=(512,260)8 dur=4 res=0x1 s={false 0} ch=false fn=-1
04-23 07:11:11.134  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:11:11.480  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:11:11.854  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:11:12.061  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:11:12.531  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:11:12.928  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:11:13.321  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:11:13.626  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:11:14.196  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:11:14.409  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:11:16.982  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:11:17.221  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:11:17.377  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 0 1
04-23 07:11:17.507  3312  3312 D InputTransport: Input channel destroyed: 'ClientS', fd=102
04-23 07:11:17.660  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: handleAppVisibility mAppVisible=true visible=false
04-23 07:11:17.670  3312  3341 D OpenGLRenderer: setSurface called with nullptr
04-23 07:11:17.670  3312  3341 D OpenGLRenderer: setSurface() destroyed EGLSurface
04-23 07:11:17.670  3312  3341 D OpenGLRenderer: destroyEglSurface
04-23 07:11:17.673  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=2 res=0x5 s={false 0} ch=true fn=160
04-23 07:11:17.678  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: stopped(true) old=false
04-23 07:11:17.687  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=2 res=0x5 s={false 0} ch=false fn=-1
04-23 07:11:21.159  3312  3341 D OpenGLRenderer: setSurface called with nullptr
04-23 07:11:21.159  3312  3312 I ViewRootImpl@247cf96[SamSprungOverlay]: dispatchDetachedFromWindow
04-23 07:11:21.164  3312  3312 D InputTransport: Input channel destroyed: 'edf72f4', fd=89
04-23 07:11:21.182  3312  3312 D skia    : --- Failed to create image decoder with message 'unimplemented'
04-23 07:11:22.317  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: handleAppVisibility mAppVisible=false visible=true
04-23 07:11:22.324  3312  3341 D OpenGLRenderer: setSurface called with nullptr
04-23 07:11:22.329  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)4 dur=5 res=0x1 s={false 0} ch=false fn=-1
04-23 07:11:22.349  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: stopped(false) old=true
04-23 07:11:22.350  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: stopped(false) old=false
04-23 07:11:22.361  3312  3341 D OpenGLRenderer: setSurface called with nullptr
04-23 07:11:22.373  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=11 res=0x7 s={true 488149212128} ch=true fn=-1
04-23 07:11:22.373  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11374 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:2893 
04-23 07:11:22.374  3312  3341 D OpenGLRenderer: eglCreateWindowSurface
04-23 07:11:22.387  3312  3341 I BufferQueueProducer: [ViewRootImpl@2c048ca[CoverPreferences]#6(BLAST Consumer)6](id:cf000000006,api:1,p:3312,c:3312) queueBuffer: queued for the first time.
04-23 07:11:22.388  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
04-23 07:11:22.388  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: [DP] rdf()
04-23 07:11:22.388  3312  3312 D ViewRootImpl@2c048ca[CoverPreferences]: reportDrawFinished (fn: -1) 
04-23 07:11:22.399  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
04-23 07:11:22.400  3312  3312 D InputMethodManager: startInputInner - Id : 0
04-23 07:11:22.400  3312  3312 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-23 07:11:23.562  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:11:23.651  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:11:27.460  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:11:27.576  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:11:27.732  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 0 1
04-23 07:11:27.847  3312  3312 D InputTransport: Input channel destroyed: 'ClientS', fd=103
04-23 07:11:28.004  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: handleAppVisibility mAppVisible=true visible=false
04-23 07:11:28.013  3312  3341 D OpenGLRenderer: setSurface called with nullptr
04-23 07:11:28.013  3312  3341 D OpenGLRenderer: setSurface() destroyed EGLSurface
04-23 07:11:28.013  3312  3341 D OpenGLRenderer: destroyEglSurface
04-23 07:11:28.016  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=2 res=0x5 s={false 0} ch=true fn=50
04-23 07:11:28.019  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: stopped(true) old=false
04-23 07:11:28.025  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=4 res=0x5 s={false 0} ch=false fn=-1
04-23 07:13:10.857  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: handleAppVisibility mAppVisible=false visible=true
04-23 07:13:10.865  3312  3341 D OpenGLRenderer: setSurface called with nullptr
04-23 07:13:10.873  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)4 dur=8 res=0x1 s={false 0} ch=false fn=-1
04-23 07:13:10.894  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: stopped(false) old=true
04-23 07:13:10.895  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: stopped(false) old=false
04-23 07:13:10.898  3312  3341 D OpenGLRenderer: setSurface called with nullptr
04-23 07:13:10.912  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=11 res=0x7 s={true 488149212128} ch=true fn=-1
04-23 07:13:10.912  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11374 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:2893 
04-23 07:13:10.913  3312  3341 D OpenGLRenderer: eglCreateWindowSurface
04-23 07:13:10.941  3312  3341 I BufferQueueProducer: [ViewRootImpl@2c048ca[CoverPreferences]#7(BLAST Consumer)7](id:cf000000007,api:1,p:3312,c:3312) queueBuffer: queued for the first time.
04-23 07:13:10.943  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
04-23 07:13:10.943  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: [DP] rdf()
04-23 07:13:10.943  3312  3312 D ViewRootImpl@2c048ca[CoverPreferences]: reportDrawFinished (fn: -1) 
04-23 07:13:10.965  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
04-23 07:13:10.966  3312  3312 D InputMethodManager: startInputInner - Id : 0
04-23 07:13:10.966  3312  3312 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-23 07:13:12.586  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:12.701  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:13.225  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:13.322  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:13.541  3312  3341 D OpenGLRenderer: setSurface called with nullptr
04-23 07:13:14.043  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:14.129  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:14.573  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:14.696  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:14.860  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 0 1
04-23 07:13:15.004  3312  3312 D InputTransport: Input channel destroyed: 'ClientS', fd=103
04-23 07:13:15.151  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: handleAppVisibility mAppVisible=true visible=false
04-23 07:13:15.161  3312  3341 D OpenGLRenderer: setSurface called with nullptr
04-23 07:13:15.161  3312  3341 D OpenGLRenderer: setSurface() destroyed EGLSurface
04-23 07:13:15.161  3312  3341 D OpenGLRenderer: destroyEglSurface
04-23 07:13:15.165  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=2 res=0x5 s={false 0} ch=true fn=148
04-23 07:13:15.169  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: stopped(true) old=false
04-23 07:13:15.179  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=4 res=0x5 s={false 0} ch=false fn=-1
04-23 07:13:31.529  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: handleAppVisibility mAppVisible=false visible=true
04-23 07:13:31.538  3312  3341 D OpenGLRenderer: setSurface called with nullptr
04-23 07:13:31.544  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)4 dur=5 res=0x1 s={false 0} ch=false fn=-1
04-23 07:13:31.565  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: stopped(false) old=true
04-23 07:13:31.593  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: stopped(false) old=false
04-23 07:13:31.594  3312  3341 D OpenGLRenderer: setSurface called with nullptr
04-23 07:13:31.609  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=14 res=0x7 s={true 488149212128} ch=true fn=-1
04-23 07:13:31.609  3312  3341 D OpenGLRenderer: eglCreateWindowSurface
04-23 07:13:31.609  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11374 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:2893 
04-23 07:13:31.630  3312  3341 I BufferQueueProducer: [ViewRootImpl@2c048ca[CoverPreferences]#8(BLAST Consumer)8](id:cf000000008,api:1,p:3312,c:3312) queueBuffer: queued for the first time.
04-23 07:13:31.632  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
04-23 07:13:31.632  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: [DP] rdf()
04-23 07:13:31.632  3312  3312 D ViewRootImpl@2c048ca[CoverPreferences]: reportDrawFinished (fn: -1) 
04-23 07:13:31.656  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
04-23 07:13:31.657  3312  3312 D InputMethodManager: startInputInner - Id : 0
04-23 07:13:31.657  3312  3312 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-23 07:13:32.105  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme key 0
04-23 07:13:32.358  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:32.362  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme key 1
04-23 07:13:33.044  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:33.374  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:34.339  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:35.922  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:36.455  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:36.850  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:37.108  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:37.633  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:37.838  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:39.150  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:39.319  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:41.318  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:41.410  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:42.355  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:42.453  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:44.946  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:45.000  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:46.686  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:46.804  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:47.919  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:49.823  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:50.550  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:50.639  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:52.029  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:52.124  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
04-23 07:13:59.321  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 0
04-23 07:13:59.404  3312  3312 I ViewRootImpl@2c048ca[CoverPreferences]: ViewPostIme pointer 1
```

**Comment by AbandonedCart** [comment] 2022-04-23 01:25
Duplicate of https://github.com/SamSprung/SamSprung-TooUI/issues/138

**Closed by AbandonedCart** 2022-04-23 01:25 UTC
