### ISSUE TITLE
[Logcat]: SamSprung #3f026ce

### ISSUE THREAD

**Issue by LogcatGitHub** [SamSprung/SamSprung-TooUI#213] opened 2022-10-29 16:52 UTC
*Submitted by andreasgp@*****.com*

Description:
---

Multiple ...documented in email.

Device info:
---
<table>
<tr><td>App version</td><td>2.1.4</td></tr>
<tr><td>App version code</td><td>214</td></tr>
<tr><td>Android build version</td><td>F7210ZSU1AVIG</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>32</td></tr>
<tr><td>Android build ID</td><td>SP2A.220305.013.F7210ZSU1AVIG</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>b4q</td></tr>
<tr><td>Device model</td><td>SM-F7210</td></tr>
<tr><td>Device product name</td><td>b4qzhx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Logcat:
---
```
SamSprung (google) #3f026ce
Android S_V2 (12)
Secure Lock Screen

--------- beginning of crash
10-28 12:25:59.173 30456 15773 E AndroidRuntime: FATAL EXCEPTION: pool-151-thread-1
10-28 12:25:59.173 30456 15773 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 30456
10-28 12:25:59.173 30456 15773 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{af8ee1a} (f618d3f1-4c0b-4287-800c-4625bbd26f95) not attached to an activity.
10-28 12:25:59.173 30456 15773 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
10-28 12:25:59.173 30456 15773 E AndroidRuntime: 	at com.eightbit.samsprung.launcher.AppDrawerFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:31)
10-28 12:25:59.173 30456 15773 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-28 12:25:59.173 30456 15773 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-28 12:25:59.173 30456 15773 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
10-28 13:16:57.849 30456 24006 E AndroidRuntime: FATAL EXCEPTION: pool-179-thread-1
10-28 13:16:57.849 30456 24006 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 30456
10-28 13:16:57.849 30456 24006 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{63e5398} (8575c5a1-db52-4bce-ab1f-bd98e6f2bd36) not attached to an activity.
10-28 13:16:57.849 30456 24006 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
10-28 13:16:57.849 30456 24006 E AndroidRuntime: 	at com.eightbit.samsprung.launcher.AppDrawerFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:31)
10-28 13:16:57.849 30456 24006 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-28 13:16:57.849 30456 24006 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-28 13:16:57.849 30456 24006 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
10-28 13:17:35.564 30456 24422 E AndroidRuntime: FATAL EXCEPTION: pool-202-thread-1
10-28 13:17:35.564 30456 24422 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 30456
10-28 13:17:35.564 30456 24422 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{a180aa5} (ced319c7-4f69-4909-8ca5-92a080f3dc7b) not attached to an activity.
10-28 13:17:35.564 30456 24422 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
10-28 13:17:35.564 30456 24422 E AndroidRuntime: 	at com.eightbit.samsprung.launcher.AppDrawerFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:31)
10-28 13:17:35.564 30456 24422 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-28 13:17:35.564 30456 24422 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-28 13:17:35.564 30456 24422 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
10-28 17:20:24.111 30456 18281 E AndroidRuntime: FATAL EXCEPTION: pool-228-thread-1
10-28 17:20:24.111 30456 18281 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 30456
10-28 17:20:24.111 30456 18281 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{e37c2c2} (d5ad59df-3adf-433c-a6b2-4cda4ae77fa5) not attached to an activity.
10-28 17:20:24.111 30456 18281 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
10-28 17:20:24.111 30456 18281 E AndroidRuntime: 	at com.eightbit.samsprung.launcher.AppDrawerFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:31)
10-28 17:20:24.111 30456 18281 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-28 17:20:24.111 30456 18281 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-28 17:20:24.111 30456 18281 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
10-28 18:35:42.044 30456 18346 E AndroidRuntime: FATAL EXCEPTION: pool-266-thread-1
10-28 18:35:42.044 30456 18346 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 30456
10-28 18:35:42.044 30456 18346 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{51b071a} (51c4ec10-fef6-4180-a974-125328936c48) not attached to an activity.
10-28 18:35:42.044 30456 18346 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
10-28 18:35:42.044 30456 18346 E AndroidRuntime: 	at com.eightbit.samsprung.launcher.AppDrawerFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:31)
10-28 18:35:42.044 30456 18346 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-28 18:35:42.044 30456 18346 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-28 18:35:42.044 30456 18346 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
--------- beginning of main
10-29 09:50:57.859  6306  6306 E prung:SamSprun: Not starting debugger since process cannot load the jdwp agent.
10-29 09:50:57.860  6306  6306 E USNET   : USNET: appName: com.eightbit.samsprung:SamSprung
10-29 09:50:57.922  6306  6306 W prung:SamSprun: Entry not found
10-29 09:50:57.922  6306  6306 W prung:SamSprun: Entry not found
10-29 09:50:57.923  6306  6306 W prung:SamSprun: Entry not found
10-29 09:50:57.923  6306  6306 W prung:SamSprun: Entry not found
10-29 09:50:57.926  6306  6306 W prung:SamSprun: JIT profile information will not be recorded: profile file does not exist.
10-29 09:50:57.926  6306  6306 W prung:SamSprun: JIT profile information will not be recorded: profile file does not exist.
10-29 09:50:57.926  6306  6306 W prung:SamSprun: JIT profile information will not be recorded: profile file does not exist.
10-29 09:50:57.926  6306  6306 W prung:SamSprun: JIT profile information will not be recorded: profile file does not exist.
10-29 09:50:57.964  6306  6336 W Adreno-AppProfiles: Could not find QSPM HAL service. Skipping adreno profile processing.
10-29 09:50:58.016  6306  6306 W prung:SamSprun: Entry not found
10-29 09:50:58.084  6306  6351 W chromium: [WARNING:dns_config_service_android.cc(115)] Failed to read DnsConfig.
10-29 09:51:00.020  6306  6382 W cr_media: Requires BLUETOOTH permission
```

**Comment by AbandonedCart** [comment] 2022-10-29 17:02
Duplicate of https://github.com/SamSprung/SamSprung-TooUI/issues/212

**Comment by AbandonedCart** [comment] 2022-10-29 17:02
```
10-27 23:22:59.762  2999  3827 E AndroidRuntime: FATAL EXCEPTION: pool-1417-thread-1
10-27 23:22:59.762  2999  3827 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 2999
10-27 23:22:59.762  2999  3827 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{af9e7c2} (736c07f0-b950-49e5-bf5d-64de29c5949c) not attached to an activity.
10-27 23:22:59.762  2999  3827 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
10-27 23:22:59.762  2999  3827 E AndroidRuntime: 	at com.eightbit.samsprung.launcher.AppDrawerFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:31)
10-27 23:22:59.762  2999  3827 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-27 23:22:59.762  2999  3827 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-27 23:22:59.762  2999  3827 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-27 23:28:12.097  2999  8111 E AndroidRuntime: FATAL EXCEPTION: pool-1666-thread-1
10-27 23:28:12.097  2999  8111 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 2999
10-27 23:28:12.097  2999  8111 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{c99cabf} (984bca0d-6840-444e-8b16-1b435153eccc) not attached to an activity.
10-27 23:28:12.097  2999  8111 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
10-27 23:28:12.097  2999  8111 E AndroidRuntime: 	at com.eightbit.samsprung.launcher.AppDrawerFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:31)
10-27 23:28:12.097  2999  8111 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-27 23:28:12.097  2999  8111 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-27 23:28:12.097  2999  8111 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-27 23:28:51.341  2999  8543 E AndroidRuntime: FATAL EXCEPTION: pool-1794-thread-1
10-27 23:28:51.341  2999  8543 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 2999
10-27 23:28:51.341  2999  8543 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{d988f60} (cdbe9d4c-5a94-4ee3-a8d4-d93a07f1d4d7) not attached to an activity.
10-27 23:28:51.341  2999  8543 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
10-27 23:28:51.341  2999  8543 E AndroidRuntime: 	at com.eightbit.samsprung.launcher.AppDrawerFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:31)
10-27 23:28:51.341  2999  8543 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-27 23:28:51.341  2999  8543 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-27 23:28:51.341  2999  8543 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-27 23:29:03.962  2999  8786 E AndroidRuntime: FATAL EXCEPTION: pool-1808-thread-1
10-27 23:29:03.962  2999  8786 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 2999
10-27 23:29:03.962  2999  8786 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{700b537} (ef3fa59b-5618-40a0-9321-5e09f2f1f9f4) not attached to an activity.
10-27 23:29:03.962  2999  8786 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
10-27 23:29:03.962  2999  8786 E AndroidRuntime: 	at com.eightbit.samsprung.launcher.AppDrawerFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:31)
10-27 23:29:03.962  2999  8786 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-27 23:29:03.962  2999  8786 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-27 23:29:03.962  2999  8786 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-28 17:08:50.247  2999  8244 E AndroidRuntime: FATAL EXCEPTION: pool-2350-thread-1
10-28 17:08:50.247  2999  8244 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 2999
10-28 17:08:50.247  2999  8244 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{2e687d8} (e3c26a62-3a54-49c2-9550-e2e476fdc9c6) not attached to an activity.
10-28 17:08:50.247  2999  8244 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
10-28 17:08:50.247  2999  8244 E AndroidRuntime: 	at com.eightbit.samsprung.launcher.AppDrawerFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:31)
10-28 17:08:50.247  2999  8244 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-28 17:08:50.247  2999  8244 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-28 17:08:50.247  2999  8244 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-28 17:08:58.334  2999  8736 E AndroidRuntime: FATAL EXCEPTION: pool-2374-thread-1
10-28 17:08:58.334  2999  8736 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 2999
10-28 17:08:58.334  2999  8736 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{afaa72} (35b3bb5c-fff4-4ae3-899c-9ce00d7c975e) not attached to an activity.
10-28 17:08:58.334  2999  8736 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
10-28 17:08:58.334  2999  8736 E AndroidRuntime: 	at com.eightbit.samsprung.launcher.AppDrawerFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:31)
10-28 17:08:58.334  2999  8736 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-28 17:08:58.334  2999  8736 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-28 17:08:58.334  2999  8736 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-28 17:09:22.499  2999  9031 E AndroidRuntime: FATAL EXCEPTION: pool-2479-thread-1
10-28 17:09:22.499  2999  9031 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 2999
10-28 17:09:22.499  2999  9031 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{3daa64d} (47ad1db3-641e-497b-ac76-f3868e3565a3) not attached to an activity.
10-28 17:09:22.499  2999  9031 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
10-28 17:09:22.499  2999  9031 E AndroidRuntime: 	at com.eightbit.samsprung.launcher.AppDrawerFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:31)
10-28 17:09:22.499  2999  9031 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-28 17:09:22.499  2999  9031 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-28 17:09:22.499  2999  9031 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-29 13:42:45.838  2999 24262 E AndroidRuntime: FATAL EXCEPTION: pool-3343-thread-1
10-29 13:42:45.838  2999 24262 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 2999
10-29 13:42:45.838  2999 24262 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{e77c441} (163b8371-9b3b-4358-9e38-f543cb6f8d1c) not attached to an activity.
10-29 13:42:45.838  2999 24262 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
10-29 13:42:45.838  2999 24262 E AndroidRuntime: 	at com.eightbit.samsprung.launcher.AppDrawerFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:31)
10-29 13:42:45.838  2999 24262 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-29 13:42:45.838  2999 24262 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-29 13:42:45.838  2999 24262 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-29 13:42:58.088  2999 24709 E AndroidRuntime: FATAL EXCEPTION: pool-3368-thread-1
10-29 13:42:58.088  2999 24709 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 2999
10-29 13:42:58.088  2999 24709 E AndroidRuntime: java.lang.IllegalStateException: Fragment AppDrawerFragment{12d8264} (4d7c877d-b4fa-43cd-bcc6-d3325883dd8c) not attached to an activity.
10-29 13:42:58.088  2999 24709 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
10-29 13:42:58.088  2999 24709 E AndroidRuntime: 	at com.eightbit.samsprung.launcher.AppDrawerFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:31)
10-29 13:42:58.088  2999 24709 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-29 13:42:58.088  2999 24709 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-29 13:42:58.088  2999 24709 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
```

**Closed as completed by AbandonedCart** 2022-10-29 17:02 UTC
