### ISSUE TITLE
[Logcat]: SamSprung #483676d

### ISSUE THREAD

**Issue by LogcatGitHub** [SamSprung/SamSprung-TooUI#221] opened 2022-11-22 18:50 UTC
*Submitted by gga_9210@****.fr*

Description:
---

Crash after last update

Device info:
---
<table>
<tr><td>App version</td><td>2.2.0</td></tr>
<tr><td>App version code</td><td>220</td></tr>
<tr><td>Android build version</td><td>F711BXXS3CVIG</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>32</td></tr>
<tr><td>Android build ID</td><td>SP2A.220305.013.F711BXXS3CVIG</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>b2q</td></tr>
<tr><td>Device model</td><td>SM-F711B</td></tr>
<tr><td>Device product name</td><td>b2qxxx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Logcat:
---
```
SamSprung (github) #483676d
Android S_V2 (12)
Secure Lock Screen

--------- beginning of main
11-22 12:50:10.007 27256 27256 D AndroidRuntime: Shutting down VM
--------- beginning of crash
11-22 12:50:10.008 27256 27256 E AndroidRuntime: FATAL EXCEPTION: main
11-22 12:50:10.008 27256 27256 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 27256
11-22 12:50:10.008 27256 27256 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.eightbit.samsprung/com.eightbit.samsprung.SamSprungOverlay}: java.lang.IllegalStateException: Fragment NotificationFragment{dfa32b0} (e85b780d-877a-4d99-982e-9a7cacc3ae9f) not attached to an activity.
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4102)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4403)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:104)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2498)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8855)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Fragment NotificationFragment{dfa32b0} (e85b780d-877a-4d99-982e-9a7cacc3ae9f) not attached to an activity.
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at com.eightbit.samsprung.drawer.NotificationFragment.<init>(NotificationFragment.kt:4)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at com.eightbit.samsprung.drawer.CoverStateAdapter.<init>(CoverStateAdapter.kt:25)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at com.eightbit.samsprung.SamSprungOverlay.<init>(SamSprungOverlay.kt:27)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:1)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1291)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4089)
11-22 12:50:10.008 27256 27256 E AndroidRuntime: 	... 12 more
11-22 12:50:10.064 27256 27256 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
11-22 12:50:10.244 28941 28941 E prung:SamSprun: Not starting debugger since process cannot load the jdwp agent.
11-22 12:50:10.246 28941 28941 E USNET   : USNET: appName: com.eightbit.samsprung:SamSprung
11-22 12:50:10.313 28941 28941 D AndroidRuntime: Shutting down VM
11-22 12:50:10.313 28941 28941 E AndroidRuntime: FATAL EXCEPTION: main
11-22 12:50:10.313 28941 28941 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 28941
11-22 12:50:10.313 28941 28941 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.eightbit.samsprung/com.eightbit.samsprung.SamSprungOverlay}: java.lang.IllegalStateException: Fragment NotificationFragment{b378a0a} (78baa441-e35b-451b-b8de-a58f8fdfbdaa) not attached to an activity.
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4102)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4403)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:104)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2498)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8855)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Fragment NotificationFragment{b378a0a} (78baa441-e35b-451b-b8de-a58f8fdfbdaa) not attached to an activity.
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at com.eightbit.samsprung.drawer.NotificationFragment.<init>(NotificationFragment.kt:4)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at com.eightbit.samsprung.drawer.CoverStateAdapter.<init>(CoverStateAdapter.kt:25)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at com.eightbit.samsprung.SamSprungOverlay.<init>(SamSprungOverlay.kt:27)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:1)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1291)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4089)
11-22 12:50:10.313 28941 28941 E AndroidRuntime: 	... 12 more
11-22 12:50:10.333 28941 28941 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
11-22 12:50:10.387 28979 28979 E prung:SamSprun: Not starting debugger since process cannot load the jdwp agent.
11-22 12:50:10.388 28979 28979 E USNET   : USNET: appName: com.eightbit.samsprung:SamSprung
11-22 12:50:10.437 28979 28979 D AndroidRuntime: Shutting down VM
11-22 12:50:10.437 28979 28979 E AndroidRuntime: FATAL EXCEPTION: main
11-22 12:50:10.437 28979 28979 E AndroidRuntime: Process: com.eightbit.samsprung:SamSprung, PID: 28979
11-22 12:50:10.437 28979 28979 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.eightbit.samsprung/com.eightbit.samsprung.SamSprungOverlay}: java.lang.IllegalStateException: Fragment NotificationFragment{b378a0a} (6d05c9a0-59cc-430f-a67c-1b8031dc161a) not attached to an activity.
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4102)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4403)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:104)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2498)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8855)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Fragment NotificationFragment{b378a0a} (6d05c9a0-59cc-430f-a67c-1b8031dc161a) not attached to an activity.
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:38)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at com.eightbit.samsprung.drawer.NotificationFragment.<init>(NotificationFragment.kt:4)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at com.eightbit.samsprung.drawer.CoverStateAdapter.<init>(CoverStateAdapter.kt:25)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at com.eightbit.samsprung.SamSprungOverlay.<init>(SamSprungOverlay.kt:27)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:1)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1291)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4089)
11-22 12:50:10.437 28979 28979 E AndroidRuntime: 	... 12 more
11-22 12:50:10.470 28979 28979 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
11-22 12:50:11.928 29026 29026 E prung:SamSprun: Not starting debugger since process cannot load the jdwp agent.
11-22 12:50:11.930 29026 29026 E USNET   : USNET: appName: com.eightbit.samsprung:SamSprung
11-22 12:50:12.041 29026 29026 W ziparchive: Unable to open '/data/app/~~ssr8_BxZAv1RnLS4FlWsiQ==/com.google.android.trichromelibrary_530410534-FksRPPUEp4AYgENAPT31IA==/base.dm': No such file or directory
11-22 12:50:12.041 29026 29026 W ziparchive: Unable to open '/data/app/~~ssr8_BxZAv1RnLS4FlWsiQ==/com.google.android.trichromelibrary_530410534-FksRPPUEp4AYgENAPT31IA==/base.dm': No such file or directory
11-22 12:50:12.041 29026 29026 W prung:SamSprun: Entry not found
11-22 12:50:12.088 29026 29064 W chromium: [WARNING:dns_config_service_android.cc(115)] Failed to read DnsConfig.
11-22 12:50:12.963 29026 29026 W Choreographer: Frame time is 0.052802 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
11-22 12:50:18.102 29026 29026 W Choreographer: Frame time is 0.063531 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
11-22 12:50:33.257 29026 29026 E prung:SamSprun: No package ID ff found for ID 0xfffffffe.
```

**Comment by AbandonedCart** [comment] 2022-11-22 18:55
Duplicate of https://github.com/SamSprung/SamSprung-TooUI/issues/220

**Closed as completed by AbandonedCart** 2022-11-22 18:55 UTC
