### ISSUE TITLE
Logcat - SamSprung #6e4e048

### ISSUE THREAD

**Issue by LogcatGitHub** [SamSprung/SamSprung-TooUI#139] opened 2022-04-22 23:16 UTC
*Submitted by Kanokrada.tungkamanee@*****.com*

Description:
---

Kanokrada.tungkamanee@gmail.com 

Device info:
---
<table>
<tr><td>App version</td><td>1.6.3</td></tr>
<tr><td>App version code</td><td>163</td></tr>
<tr><td>Android build version</td><td>F711BXXS2CVC9</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SP1A.210812.016.F711BXXS2CVC9</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>b2q</td></tr>
<tr><td>Device model</td><td>SM-F711B</td></tr>
<tr><td>Device product name</td><td>b2qxxx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Logcat:
---
```SamSprung - #6e4e048
Android S (12)
Secure Lock Screen

--------- beginning of main
04-23 06:14:12.206  9948 29792 I LiveIconLoader: [Calendar] LiveIcon - stdIconSize : 144 , targetIconSize : 144
04-23 06:14:12.206  9948 29792 W LiveIconLoader: System font not found, reverting to Roboto.
04-23 06:14:12.208  9948 29792 I LiveIconLoader: [Calendar] getLiveIcon - Date: 23
04-23 06:14:12.210  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=9 res=0x7 s={true 488149220848} ch=true fn=-1
04-23 06:14:12.210  9948  9974 D OpenGLRenderer: eglCreateWindowSurface
04-23 06:14:12.212  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11374 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:2893 
04-23 06:14:12.229  9948  9974 I BufferQueueProducer: [ViewRootImpl@a7d75b5[CoverPreferences]#3(BLAST Consumer)3](id:26dc00000003,api:1,p:9948,c:9948) queueBuffer: queued for the first time.
04-23 06:14:12.230  9948  9974 D OpenGLRenderer: GPIS:: SetUp Pid : 9948    Tid : 9974
04-23 06:14:12.231  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
04-23 06:14:12.231  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: [DP] rdf()
04-23 06:14:12.231  9948  9948 D ViewRootImpl@a7d75b5[CoverPreferences]: reportDrawFinished (fn: -1) 
04-23 06:14:12.231  9948  9948 D skia    : --- Failed to create image decoder with message 'unimplemented'
04-23 06:14:12.233  9948  9948 D WallpaperManager: peekWallpaperBitmap: which =1, useCache = true
04-23 06:14:12.233  9948  9948 D WallpaperManager: peekWallpaperBitmap() cached image height=2640 width=1160
04-23 06:14:12.235  9948  9958 W System  : A resource failed to call close. 
04-23 06:14:12.262  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
04-23 06:14:12.263  9948  9948 D InputMethodManager: startInputInner - Id : 0
04-23 06:14:12.263  9948  9948 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-23 06:14:12.396  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:13.013  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:19.274  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:20.653  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:23.305  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:23.424  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:24.905  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:25.383  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:27.930  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:28.046  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:28.291  9948  9974 D OpenGLRenderer: setSurface called with nullptr
04-23 06:14:30.092  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:30.344  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:33.321  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:33.448  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:34.272  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:34.448  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:35.817  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:35.925  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:37.435  9948  9948 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=true
04-23 06:14:37.443  9948  9948 I ViewRootImpl@bc37562[SamSprungOverlay]: Relayout returned: old=(0,245,512,260) new=(0,245,512,260) req=(512,15)8 dur=7 res=0x1 s={false 0} ch=false fn=-1
04-23 06:14:39.815  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:40.002  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:40.938  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:41.283  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:41.711  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:41.819  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:42.652  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:43.073  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:44.851  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:44.947  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:45.366  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:45.588  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:46.857  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:46.986  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:48.208  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:48.327  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:50.797  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:50.967  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:52.680  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:52.876  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:54.035  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:54.480  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:56.785  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:57.332  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:14:58.532  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:14:59.185  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:15:00.558  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 0 1
04-23 06:15:00.571  9948  9948 D InputTransport: Input channel destroyed: 'ClientS', fd=140
04-23 06:15:01.908  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
04-23 06:15:01.909  9948  9948 D InputMethodManager: startInputInner - Id : 0
04-23 06:15:01.909  9948  9948 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-23 06:15:03.046  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:15:03.477  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:15:04.580  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:15:04.675  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:15:04.739  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 0 1
04-23 06:15:04.958  9948  9948 D InputTransport: Input channel destroyed: 'ClientS', fd=102
04-23 06:15:05.338  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: handleAppVisibility mAppVisible=true visible=false
04-23 06:15:05.349  9948  9974 D OpenGLRenderer: setSurface called with nullptr
04-23 06:15:05.349  9948  9974 D OpenGLRenderer: setSurface() destroyed EGLSurface
04-23 06:15:05.350  9948  9974 D OpenGLRenderer: destroyEglSurface
04-23 06:15:05.354  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=4 res=0x5 s={false 0} ch=true fn=914
04-23 06:15:05.358  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: stopped(true) old=false
04-23 06:15:05.364  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=2 res=0x5 s={false 0} ch=false fn=-1
04-23 06:15:43.976  9948  9974 D OpenGLRenderer: setSurface called with nullptr
04-23 06:15:43.976  9948  9948 I ViewRootImpl@bc37562[SamSprungOverlay]: dispatchDetachedFromWindow
04-23 06:15:43.980  9948  9948 D InputTransport: Input channel destroyed: 'f0409a9', fd=95
04-23 06:15:43.990  9948  9948 D skia    : --- Failed to create image decoder with message 'unimplemented'
04-23 06:15:53.937  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: handleAppVisibility mAppVisible=false visible=true
04-23 06:15:53.945  9948  9974 D OpenGLRenderer: setSurface called with nullptr
04-23 06:15:53.949  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)4 dur=3 res=0x1 s={false 0} ch=false fn=-1
04-23 06:15:53.969  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: stopped(false) old=true
04-23 06:15:53.972  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: stopped(false) old=false
04-23 06:15:53.972  9948  9948 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
04-23 06:15:53.980  9948  9974 D OpenGLRenderer: setSurface called with nullptr
04-23 06:15:53.989  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=6 res=0x7 s={true 488149220848} ch=true fn=-1
04-23 06:15:53.989  9948  9974 D OpenGLRenderer: eglCreateWindowSurface
04-23 06:15:53.990  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11374 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:2893 
04-23 06:15:54.022  9948  9974 I BufferQueueProducer: [ViewRootImpl@a7d75b5[CoverPreferences]#4(BLAST Consumer)4](id:26dc00000004,api:1,p:9948,c:9948) queueBuffer: queued for the first time.
04-23 06:15:54.023  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
04-23 06:15:54.023  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: [DP] rdf()
04-23 06:15:54.023  9948  9948 D ViewRootImpl@a7d75b5[CoverPreferences]: reportDrawFinished (fn: -1) 
04-23 06:15:54.050  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
04-23 06:15:54.051  9948  9948 D InputMethodManager: startInputInner - Id : 0
04-23 06:15:54.051  9948  9948 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-23 06:15:54.139  9948  9974 D OpenGLRenderer: setSurface called with nullptr
04-23 06:15:55.143  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:15:55.472  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:15:55.830  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:15:56.191  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:15:56.631  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:15:56.738  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:15:57.064  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:15:57.169  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:15:57.868  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:15:58.077  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:15:58.480  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:15:58.577  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:15:59.534  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:15:59.684  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:16:00.372  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:16:00.725  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:16:01.288  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:16:01.775  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:16:02.062  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:16:02.398  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:16:02.610  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:16:02.722  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:16:02.850  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:16:03.240  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:16:04.177  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:16:04.238  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:16:05.030  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:16:05.431  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:16:05.649  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:16:05.714  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:16:06.930  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:16:07.054  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:16:07.169  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 0 1
04-23 06:16:07.192  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: stopped(false) old=false
04-23 06:16:07.192  9948  9948 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
04-23 06:16:07.201  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=8 res=0x1 s={true 488149220848} ch=false fn=133
04-23 06:16:07.213  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
04-23 06:16:07.214  9948  9948 D InputMethodManager: startInputInner - Id : 0
04-23 06:16:07.214  9948  9948 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-23 06:16:07.787  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:16:07.895  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:16:07.961  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 0 1
04-23 06:16:07.983  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: stopped(false) old=false
04-23 06:16:07.983  9948  9948 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
04-23 06:16:07.994  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=10 res=0x1 s={true 488149220848} ch=false fn=168
04-23 06:16:08.005  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
04-23 06:16:08.005  9948  9948 D InputMethodManager: startInputInner - Id : 0
04-23 06:16:08.005  9948  9948 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-23 06:16:08.878  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:16:09.136  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:16:11.535  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:16:11.667  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:16:14.903  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:16:15.074  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:16:16.187  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:16:16.314  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:16:16.597  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 0 1
04-23 06:16:16.828  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: handleAppVisibility mAppVisible=true visible=false
04-23 06:16:16.837  9948  9974 D OpenGLRenderer: setSurface called with nullptr
04-23 06:16:16.837  9948  9974 D OpenGLRenderer: setSurface() destroyed EGLSurface
04-23 06:16:16.837  9948  9974 D OpenGLRenderer: destroyEglSurface
04-23 06:16:16.841  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=1 res=0x5 s={false 0} ch=true fn=290
04-23 06:16:18.449  9948  9948 D InputTransport: Input channel destroyed: 'ClientS', fd=115
04-23 06:16:18.474  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: stopped(true) old=false
04-23 06:16:18.480  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)8 dur=3 res=0x5 s={false 0} ch=false fn=-1
04-23 06:16:19.830  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: handleAppVisibility mAppVisible=false visible=true
04-23 06:16:19.836  9948  9974 D OpenGLRenderer: setSurface called with nullptr
04-23 06:16:19.853  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)4 dur=17 res=0x1 s={false 0} ch=false fn=-1
04-23 06:16:19.873  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: stopped(false) old=true
04-23 06:16:19.873  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: stopped(false) old=false
04-23 06:16:19.879  9948  9974 D OpenGLRenderer: setSurface called with nullptr
04-23 06:16:19.890  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=11 res=0x7 s={true 488149220848} ch=true fn=-1
04-23 06:16:19.891  9948  9974 D OpenGLRenderer: eglCreateWindowSurface
04-23 06:16:19.891  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11374 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:2893 
04-23 06:16:19.909  9948  9974 I BufferQueueProducer: [ViewRootImpl@a7d75b5[CoverPreferences]#5(BLAST Consumer)5](id:26dc00000005,api:1,p:9948,c:9948) queueBuffer: queued for the first time.
04-23 06:16:19.911  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
04-23 06:16:19.911  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: [DP] rdf()
04-23 06:16:19.911  9948  9948 D ViewRootImpl@a7d75b5[CoverPreferences]: reportDrawFinished (fn: -1) 
04-23 06:16:19.927  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
04-23 06:16:19.928  9948  9948 D InputMethodManager: startInputInner - Id : 0
04-23 06:16:19.928  9948  9948 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-23 06:16:21.239  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:16:21.729  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
04-23 06:16:23.170  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 0
04-23 06:16:23.479  9948  9948 I ViewRootImpl@a7d75b5[CoverPreferences]: ViewPostIme pointer 1
```

**Comment by AbandonedCart** [comment] 2022-04-23 01:24
Duplicate of https://github.com/SamSprung/SamSprung-TooUI/issues/138

**Closed by AbandonedCart** 2022-04-23 01:24 UTC
